dist: trusty
sudo: required
language: node_js
node_js:
  - "8"
cache: pip
install:
  - sudo pip install cookiecutter
script:
  - cookiecutter --no-input gh:rrwen/cookiecutter-reveal
  - cd template_name
  - npm install
  - npm run html
  - npm run pdf
