on: pull_request

name: Deploy

jobs:

  deploy:
    runs-on: ubuntu-latest
    name: build and upload
    steps:
      # Checkout the source code so we have some files to look at.
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: make install
      - run: make html
      - run: make pdf
