on: pull_request

name: Build

jobs:

  deploy:
    runs-on: ubuntu-latest
    name: build
    steps:
      # Checkout the source code so we have some files to look at.
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: make install
      - run: make html
      - run: make pdf
