on:
  push:
    branches:
      - "main"

name: Deploy

permissions:
  contents: write

jobs:

  deploy:
    runs-on: ubuntu-latest
    name: build and upload
    steps:
      # Checkout the source code so we have some files to look at.
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: |
            python -m pip install cookiecutter build pre-commit
            git config --global user.email "rene.fritze@wwu.de"
            git config --global user.name "René Fritze"
            git config --global init.defaultBranch main
      - name: Render cookiecutter
        run: cookiecutter -v --no-input -f -o /tmp/ . directory_name=cookie_reveal
      - run: make -C /tmp/cookie_reveal install
      - run: make -C /tmp/cookie_reveal html
      - run: make -C /tmp/cookie_reveal pdf
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: /tmp/cookie_reveal/static_html/
      - uses: actions/upload-artifact@v3
        with:
          name: pdf-slides
          path: -C /tmp/cookie_reveal/slides/*pdf
